services:
  nadamu-unlocker-lab:
    build:
      context: .
      dockerfile: Containerfile
    container_name: nadamu-unlocker-lab
    restart: no
    devices:
      - /dev/kvm:/dev/kvm
    networks:
      - agent_net
    volumes:
      - ./data:/lab/data
      - .:/lab/scripts:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    environment:
      - LUKS_PASSWORD=password

networks:
  agent_net:
    external: true
