FROM docker.io/kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -o Acquire::Retries=5 install -y --fix-missing --no-install-recommends \
    qemu-system-x86 \
    qemu-utils \
    cryptsetup-bin \
    cryptsetup-initramfs \
    cryptsetup \
    dropbear-initramfs \
    dropbear-bin \
    busybox \
    linux-image-amd64 \
    initramfs-tools \
    e2fsprogs \
    openssh-client \
    cpio \
    curl \
    ca-certificates \
    iproute2 \
    isc-dhcp-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /lab

COPY . /lab/
RUN chmod +x /lab/*.sh 2>/dev/null || true

ENTRYPOINT ["/lab/entrypoint.sh"]
